/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.online.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the App service. Represents a row in the &quot;online_App&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.online.model.impl.AppModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.online.model.impl.AppImpl}.
 * </p>
 *
 * @author pisw
 * @see App
 * @see com.liferay.online.model.impl.AppImpl
 * @see com.liferay.online.model.impl.AppModelImpl
 * @generated
 */
@ProviderType
public interface AppModel extends BaseModel<App>, GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a app model instance should use the {@link App} interface instead.
	 */

	/**
	 * Returns the primary key of this app.
	 *
	 * @return the primary key of this app
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this app.
	 *
	 * @param primaryKey the primary key of this app
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the online app ID of this app.
	 *
	 * @return the online app ID of this app
	 */
	public long getOnlineAppId();

	/**
	 * Sets the online app ID of this app.
	 *
	 * @param onlineAppId the online app ID of this app
	 */
	public void setOnlineAppId(long onlineAppId);

	/**
	 * Returns the app name of this app.
	 *
	 * @return the app name of this app
	 */
	@AutoEscape
	public String getAppName();

	/**
	 * Sets the app name of this app.
	 *
	 * @param appName the app name of this app
	 */
	public void setAppName(String appName);

	/**
	 * Returns the app body of this app.
	 *
	 * @return the app body of this app
	 */
	@AutoEscape
	public String getAppBody();

	/**
	 * Sets the app body of this app.
	 *
	 * @param appBody the app body of this app
	 */
	public void setAppBody(String appBody);

	/**
	 * Returns the group ID of this app.
	 *
	 * @return the group ID of this app
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this app.
	 *
	 * @param groupId the group ID of this app
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this app.
	 *
	 * @return the company ID of this app
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this app.
	 *
	 * @param companyId the company ID of this app
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this app.
	 *
	 * @return the user ID of this app
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this app.
	 *
	 * @param userId the user ID of this app
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this app.
	 *
	 * @return the user uuid of this app
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this app.
	 *
	 * @param userUuid the user uuid of this app
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this app.
	 *
	 * @return the user name of this app
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this app.
	 *
	 * @param userName the user name of this app
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this app.
	 *
	 * @return the create date of this app
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this app.
	 *
	 * @param createDate the create date of this app
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this app.
	 *
	 * @return the modified date of this app
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this app.
	 *
	 * @param modifiedDate the modified date of this app
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the app description of this app.
	 *
	 * @return the app description of this app
	 */
	@AutoEscape
	public String getAppDescription();

	/**
	 * Sets the app description of this app.
	 *
	 * @param appDescription the app description of this app
	 */
	public void setAppDescription(String appDescription);

	/**
	 * Returns the app language of this app.
	 *
	 * @return the app language of this app
	 */
	@AutoEscape
	public String getAppLanguage();

	/**
	 * Sets the app language of this app.
	 *
	 * @param appLanguage the app language of this app
	 */
	public void setAppLanguage(String appLanguage);

	/**
	 * Returns the release of this app.
	 *
	 * @return the release of this app
	 */
	@AutoEscape
	public String getRelease();

	/**
	 * Sets the release of this app.
	 *
	 * @param release the release of this app
	 */
	public void setRelease(String release);

	/**
	 * Returns the live of this app.
	 *
	 * @return the live of this app
	 */
	public boolean getLive();

	/**
	 * Returns <code>true</code> if this app is live.
	 *
	 * @return <code>true</code> if this app is live; <code>false</code> otherwise
	 */
	public boolean isLive();

	/**
	 * Sets whether this app is live.
	 *
	 * @param live the live of this app
	 */
	public void setLive(boolean live);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.online.model.App app);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.online.model.App> toCacheModel();

	@Override
	public com.liferay.online.model.App toEscapedModel();

	@Override
	public com.liferay.online.model.App toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}